### ISSUE TITLE
Anchor configuration parameters

### ISSUE THREAD

**Issue by fnobis** [lucastabelini/LaneATT#107]
I am currently testing different anchor configurations. For this. I changed the anchor configuration in
[this line](https://github.com/lucastabelini/LaneATT/blob/2f8583ba14eccba05e6779668bc3a38bc751984a/lib/models/laneatt.py#L46) to `self.anchors, self.anchors_cut = self.generate_anchors(lateral_n=0, bottom_n=1)`
I would expect that the anchors will only originate from the bottom of the image. However, I get anchors on the right side of the image.  Is there a way to plot the ground truth data as an overlay to the anchors?

![Screenshot from 2022-04-07 09-54-29](https://user-images.githubusercontent.com/36134338/162149343-e399f56a-ace6-4554-adaf-92f5825891c6.png)

**Comment by fnobis** [comment]
I found this is just an issue with the configured image width, setting the drawn image size in `gen_anchor_mask.py` to the one specified as the input size in the network solved it.

However, I am still not  sure what cut_ys exactly are and how the matching procedure works in detail. I understand that the cut_ys are used to pool the features alone the anchor lines but Ia m not sure how that works exactly. Is there any additional information on this or could you explain in a few sentences here?

Much appreciated.

**Comment by lucastabelini** [comment]
The procedure is described in the [paper](https://openaccess.thecvf.com/content/CVPR2021/html/Tabelini_Keep_Your_Eyes_on_the_Lane_Real-Time_Attention-Guided_Lane_Detection_CVPR_2021_paper.html) on Section 3.3. In terms of the implementation, the code generates (in the `compute_anchor_cut_indices` function) three vectors (`cut_xs`, `cut_ys` and `cut_zs`) that contain the indexes of the points in the image that compose an anchor. That is, the indexes of the image that intersect that anchor, as explained in the paper. Since the images have a fixed size, those indices only need to be computed once. Then, during the forward propagation those indices are used to pool each anchor's features.
