### ISSUE TITLE
The meaning of nms_topk (nms_topk: 3000) of train_parameters in config file?

### ISSUE THREAD

**Issue by sjtuljw520** [lucastabelini/LaneATT#114]
Hello, I find this is a parameter named "nms_topk" in train_parameters and was set as 3000 (nms_topk: 3000).
I can not find the discription of this parameter in the paper, anyone can help me? thank you!

**Comment by GongDianCheng** [comment]
You can find nms_topk in  lib/models/laneatt.py
Combined with the context, I think this parameter means that NMS is proposed for the first n lane lines。

**Comment by lucastabelini** [comment]
The `nms_topk` parameter controls how many lane proposals are used. That is, the NMS procedure will return the `nms_topk` proposals with the highest score that are distant enough from each other. This speeds up the model a bit since not all proposals have to be processed using NMS. During training, it is set to a value (3000) higher than the maximum number of proposals (1000) so that no proposals is ignored. During inference, it is set to a much smaller value (~4) to save computational time.

**Comment by sjtuljw520** [comment]
Many thanks for the explaining, I got it now, :) @lucastabelini @GongDianCheng
