### ISSUE TITLE
Elaboration on anchor lane proposal implementation

### ISSUE THREAD

**Issue by BatmanofZuhandArrgh** [lucastabelini/LaneATT#42]
I have been reading Lucas' code, and am a bit lost on your implementation of anchor proposal, including things like what's the need for anchor_cut, or function cut_anchor_feature and compute_anchor_cut_indices. 

It would be very helpful if Lucas or someone can add some comments explaining how those work in more details.

Thank you

**Comment by sunshine411** [comment]
I have the same confused, hope to further explanation。

Thank you

**Comment by lucastabelini** [comment]
Those functions are responsible for the proposed anchor pooling method mentioned in section 3.3 of the paper. Since for a fixed image size the regions pooled are always fixed, when the model is instantiated the indices (used in the `cut_anchor_feature` function [here](https://github.com/lucastabelini/LaneATT/blob/main/lib/models/laneatt.py#L235)) are pre-computed in the function `compute_anchor_cut_indices`.

**Comment by BatmanofZuhandArrgh** [comment]
Thanks. For anyone having this issue, rereading ROI pooling from Fast RCNN helps
