### ISSUE TITLE
Performance on culane

### ISSUE THREAD

**Issue by ztjsw** [lucastabelini/LaneATT#48]
Hi there,

I trained the resnet34 on CULane. But it only gets `{'TP': 74298, 'FP': 15827, 'FN': 30588, 'Precision': 0.8243883495145631, 'Recall': 0.7083690864367027, 'F1': 0.7619877853044187}` . It's different from the paper reports.
Is there variance on CULane training?

Thanks.

**Comment by lucastabelini** [comment]
Just like most learning-based methods, LaneATT will have some degree of variance in its results.

**Comment by ztjsw** [comment]
Ok, thank you.
By the way,  I want to ask a question about the dataset:
Why do transform in this line:
https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset.py#L55
It seems you will do transform in `__get_item__`:
https://github.com/lucastabelini/LaneATT/blob/main/lib/datasets/lane_dataset.py#L280

**Comment by lucastabelini** [comment]
The function `transform_annotations`transforms the annotations from the dataset loader (e.g., CULane's loader) to the format used by the `LaneDataset`class (a common interface for all datasets). I did this so that I would be able to change the way the data is fed to the model without having to change that on each dataset's loader. In this way, I only had to write the loader for each dataset once and then only had to work on the `LaneDataset` class.
