### ISSUE TITLE
Expected trend for batch_positivies

### ISSUE THREAD

**Issue by muragnarok** [lucastabelini/LaneATT#90]
From the code, it seems that the definition of parameter "batch_positives", that is being tracked during the training, is the number of positive matches between the proposals and the targets. When I tried to train a model with smaller resnet backbone on TuSimple data, this is what the trend of "batch_positives" looks like:
![image](https://user-images.githubusercontent.com/95242758/144903914-8151903d-ddb0-4ba9-bac6-6c9c32f81a66.png)

Is there any particular conclusion to be drawn from this? I fail to understand what this signifies?

Thanks in advance

**Comment by lucastabelini** [comment]
No, there isn't much to draw from these data. I used this mostly while debugging the model, because sometimes the number of positives would fall to 0 due to a bug in the code or a bad parameter value. There might be a case where the default anchors might not cover the necessary lanes in the dataset. In this case, the plot would show smaller numbers.
